# Python code generated by CAIT's Visual Programming Interface

import cait.essentials

face = None

rubbish_detection_pipeline_config = [
        ["version", "2021.4"], # need to explicitly specify OpenVINO version
        ["add_rgb_cam_node", 640, 360], 
        ["add_rgb_cam_preview_node"],
        ["add_stereo_cam_node", False], 
        ["add_stereo_frame_node"],
        ["add_spatial_mobilenetSSD_node", "rubbish_detection", "rubbish-detection_openvino_2021.4_5shave.blob", 300, 300, 0.5]
    ]

def setup():
    cait.essentials.initialize_component('vision', processor='oakd', mode=rubbish_detection_pipeline_config)
    
def main():
    global face
    while True:
        face = cait.essentials.detect_objects(processor='oakd', spatial=True)
        print(face)
        cait.essentials.draw_detected_objects(face)

if __name__ == "__main__":
    setup()
    main()